// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: contactspb/contacts.proto

package contactspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number []string `protobuf:"bytes,1,rep,name=number,proto3" json:"number,omitempty"`
}

func (x *ContactsRequest) Reset() {
	*x = ContactsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contactspb_contacts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactsRequest) ProtoMessage() {}

func (x *ContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contactspb_contacts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactsRequest.ProtoReflect.Descriptor instead.
func (*ContactsRequest) Descriptor() ([]byte, []int) {
	return file_contactspb_contacts_proto_rawDescGZIP(), []int{0}
}

func (x *ContactsRequest) GetNumber() []string {
	if x != nil {
		return x.Number
	}
	return nil
}

type ContactsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ContactsResponse) Reset() {
	*x = ContactsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contactspb_contacts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactsResponse) ProtoMessage() {}

func (x *ContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contactspb_contacts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactsResponse.ProtoReflect.Descriptor instead.
func (*ContactsResponse) Descriptor() ([]byte, []int) {
	return file_contactspb_contacts_proto_rawDescGZIP(), []int{1}
}

func (x *ContactsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_contactspb_contacts_proto protoreflect.FileDescriptor

var file_contactspb_contacts_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x73, 0x70, 0x62, 0x22, 0x29, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x24, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xa8, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contactspb_contacts_proto_rawDescOnce sync.Once
	file_contactspb_contacts_proto_rawDescData = file_contactspb_contacts_proto_rawDesc
)

func file_contactspb_contacts_proto_rawDescGZIP() []byte {
	file_contactspb_contacts_proto_rawDescOnce.Do(func() {
		file_contactspb_contacts_proto_rawDescData = protoimpl.X.CompressGZIP(file_contactspb_contacts_proto_rawDescData)
	})
	return file_contactspb_contacts_proto_rawDescData
}

var file_contactspb_contacts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contactspb_contacts_proto_goTypes = []interface{}{
	(*ContactsRequest)(nil),  // 0: contactspb.ContactsRequest
	(*ContactsResponse)(nil), // 1: contactspb.ContactsResponse
}
var file_contactspb_contacts_proto_depIdxs = []int32{
	0, // 0: contactspb.ContactsService.AddContacts:input_type -> contactspb.ContactsRequest
	0, // 1: contactspb.ContactsService.RemoveContacts:input_type -> contactspb.ContactsRequest
	1, // 2: contactspb.ContactsService.AddContacts:output_type -> contactspb.ContactsResponse
	1, // 3: contactspb.ContactsService.RemoveContacts:output_type -> contactspb.ContactsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contactspb_contacts_proto_init() }
func file_contactspb_contacts_proto_init() {
	if File_contactspb_contacts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contactspb_contacts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contactspb_contacts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contactspb_contacts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contactspb_contacts_proto_goTypes,
		DependencyIndexes: file_contactspb_contacts_proto_depIdxs,
		MessageInfos:      file_contactspb_contacts_proto_msgTypes,
	}.Build()
	File_contactspb_contacts_proto = out.File
	file_contactspb_contacts_proto_rawDesc = nil
	file_contactspb_contacts_proto_goTypes = nil
	file_contactspb_contacts_proto_depIdxs = nil
}
